# Site settings
title: 
subtitle: 
email: paulomoreiraesilva@gmail.com
description: Super friendly Bombay cat needs a home <br /> while his owner is away...will you keep him?
baseurl: "/mynameiscookies" # the subpath of your site, e.g. /blog
url: "https://pmoreiraesilva.github.io" # the base hostname & protocol for your site
author:
street_address: Park West 18 Jalan Lempeng 03-05
city: Singapore
state: 
zip_code: 128801
country: Singapore
phone: +65 8231 9310

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://pmoreiraesilva.github.io/mynameiscookies/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
